name: Dynamic Template

on:
  create:

jobs:
  update_templates:
    name: "Update Templates"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      # Runs a set of commands using the runners shell
      - name: Update readme.md
        run: |
          sed -i 's/<reponame>/'${{ github.event.repository.name }}'/' readme.md